### ISSUE TITLE
Documentation on how to view Quantifier Instantiations

### ISSUE THREAD

**Issue by Gopiandcode** [viperproject/axiom-profiler-2#27]
Hihi! Sorry if this isn't the right place to ask this? feel free to close if so!

I'm running the axiom profiler on some logs, and I'd like to view the concrete instantiations of an quantified axiom that z3 tried in its proof search. 

Is there a place in the UI to view this? I tried looking at the documentation, but I couldn't find anything.

**Comment by oskari1** [comment]
The nodes in the represented graph correspond to instantiations of quantified assertions and you can click on them to view the information associated with each instantiation. Do you want to view specific user-specified quantified assertions? In that case, we are planning to work on a feature which goes in that direction.

**Comment by Gopiandcode** [comment]
Ah I see, thanks for clarifying! Yes, that makes sense.
