### ISSUE TITLE
Reconnect stuck in sequences-18.log

### ISSUE THREAD

**Issue by oskari1** [viperproject/axiom-profiler-2#33]
If I open the [sequences-18.log](https://github.com/viperproject/axiom-profiler-2/files/15058507/sequences-18.log) and then apply the filter "Show quant k!354" then the tool gets stuck in the `VisibleInstGraph::reconnect` function, see [here](https://github.com/viperproject/axiom-profiler-2/blob/26783199d14a94e77a789220d9ab259edcaf90f5/smt-log-parser/src/parsers/z3/graph/visible.rs#L51). 

I've tried to limit the maximum number of edges to 1000 or so to inspect the intermediate graph of quant k!354 and saw that it adds a lot of edges, see screenshot below.
<img width="1377" alt="image" src="https://github.com/viperproject/axiom-profiler-2/assets/23278394/0bdebe83-008f-43e3-b056-a45c04d9f82a">

I'll also link two SVG files to inspect the subgraph of k!354 (dark purple nodes), once without and once with other quants:
![sequences-18-k!354_2](https://github.com/viperproject/axiom-profiler-2/assets/23278394/3704269b-fe17-41bf-a889-5f1380beb54f)
![sequences-18-k!354](https://github.com/viperproject/axiom-profiler-2/assets/23278394/d034beed-d163-424c-a058-b0dd91363ff3)

My suspicion is that it's not a correctness issue but a performance issue, due to how the equality nodes are represented in the edges of the reconnected graph.

**Comment by JonasAlaif** [comment]
@oskari1 I agree with your analysis. I expect it's probably an issue with a pattern like so:
```
   [V]
  /   \
[ ]   [ ]
  \   /
   [ ]
  /   \
[ ]   [ ]
  \   /
   [ ]
  /   \
[ ]   [ ]
  \   /
   [ ]
    |
   [V]
```
where if only the `V` nodes are visible, then one gets 2^3 indirect edges (grows exponentially with the hidden length). I think that we should change the reconnect to only consider immediate hidden children/parents, without enumerating all the paths between (such that there would only be 2 indirect edges in the above graph, for the 2 hidden children * 1 hidden parent)
